version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - pip install mkdocs
      - mkdocs build
      - pip install awscli
      - aws s3 cp site s3://bucket-man/ --recursive
  post_build:
    commands:
      - echo Build completed on `date`